# Generated by Django 2.1.5 on 2019-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('head_img', models.ImageField(upload_to='images')),
                ('Motto', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
