# Generated by Django 2.1.5 on 2019-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.CharField(help_text='文章简介', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='word_img',
            field=models.CharField(help_text='Glyphicons 字体图标', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommend',
            name='introduction',
            field=models.CharField(help_text='推荐文章简介', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='文章内容', max_length=20000000000000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(help_text='文章图片', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(help_text='文章标签', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', help_text='文章标题', max_length=100),
        ),
        migrations.AlterField(
            model_name='friends',
            name='Motto',
            field=models.CharField(help_text='座右铭或简介', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='head_img',
            field=models.ImageField(help_text='头像', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(help_text='朋友ID', max_length=10),
        ),
        migrations.AlterField(
            model_name='friends',
            name='url',
            field=models.CharField(help_text='blog 链接', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='content',
            field=models.TextField(help_text='推荐文章内容', max_length=20000000000000000),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='img',
            field=models.ImageField(help_text='推荐文章图片', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='tags',
            field=models.CharField(help_text='推荐文章标签', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='title',
            field=models.CharField(default='', help_text='推荐文章标题', max_length=100),
        ),
    ]
