# Generated by Django 2.1.5 on 2019-05-07 01:53

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20190507_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
