# Generated by Django 2.1.5 on 2019-05-07 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20190507_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='img',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='title',
        ),
        migrations.AddField(
            model_name='recommend',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blogapp.Article'),
        ),
    ]
