# Generated by Django 2.1.5 on 2019-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20190507_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='name',
            field=models.CharField(default='', help_text='（文章标题）与你选择的一样', max_length=100),
        ),
    ]
