# Generated by Django 2.1.5 on 2019-09-12 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190912_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 12, 54, 46, 124015, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
