# Generated by Django 2.1.5 on 2019-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20190503_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(help_text='关于我界面', upload_to='images')),
                ('friends_img', models.ImageField(help_text='友链界面', upload_to='images')),
                ('sort_img', models.ImageField(help_text='归档界面', upload_to='images')),
            ],
        ),
    ]
