# Generated by Django 2.1.5 on 2019-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_header_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_img',
            name='name',
            field=models.CharField(default='', help_text='组合', max_length=10),
        ),
    ]
