# Generated by Django 2.1.5 on 2019-09-12 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('intro', models.CharField(default=' A', max_length=100, verbose_name='文章简介')),
                ('content', mdeditor.fields.MDTextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 9, 12, 3, 37, 37, 353653, tzinfo=utc), verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Categories')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Images')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
