# Generated by Django 2.1.5 on 2019-09-12 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 3, 52, 21, 681740, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
