# Generated by Django 2.1.5 on 2019-09-12 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190912_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 8, 18, 7, 699825, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
