# Generated by Django 2.1.5 on 2019-09-12 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190912_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 9, 41, 23, 244990, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
