# Generated by Django 2.1.5 on 2019-09-12 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190912_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 12, 45, 13, 482262, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
