# Generated by Django 2.1.5 on 2019-09-21 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190912_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 11, 12, 12, 877668, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
