# Generated by Django 2.1.5 on 2019-09-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类名')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='button-primary', max_length=500, verbose_name='颜色')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('header_img', models.ImageField(upload_to='', verbose_name='头像')),
                ('link', models.TextField(verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名字')),
                ('img', models.ImageField(upload_to='', verbose_name='顶部图片')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='', verbose_name='头像')),
                ('QQ', models.CharField(blank=True, max_length=12, null=True, verbose_name='QQ')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('github', models.TextField(blank=True, null=True, verbose_name='github')),
            ],
        ),
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='座右铭')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标题')),
                ('font_awesome', models.TextField(verbose_name='Font Awesome')),
                ('path', models.TextField(verbose_name='地址')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='motto',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='common.Motto'),
        ),
        migrations.AddField(
            model_name='categories',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Colors'),
        ),
    ]
